name: Environments

on:
  workflow_dispatch:
    inputs:
      environment-name:
        type: environment
        default: Develop
        required: true
        description: Environment name

jobs:
  print:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-name }}
    env:
      USERNAME: ${{ vars.USERNAME }}
    steps:
      - run: echo "${USERNAME}"
