name: Environments

on:
  workflow_dispatch:
    inputs:
      environment-name:
        type: environment
        default: Develop
        required: true
        description: Environment name

jobs:
  print:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-name }}
    env:
      USERNAME: ${{ vars.USERNAME }}
    steps:
      - run: echo "UserName - '${USERNAME}'"
      - run: echo "Environment - '${{ inputs.environment-name }}'"
      - name: Develop
        if: ${{ inputs.environment-name }} == Develop
        run: echo "Develop step"
      - name: Production
        if: ${{ inputs.environment-name }} == Production
        run: echo "Production step"
