name: Environments

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        default: Develop
        required: true
        description: Environment name

jobs:
  print:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      USERNAME: ${{ vars.USERNAME }}
    steps:
      - run: echo "UserName - ${USERNAME}"
      - run: echo "Environment - ${{ inputs.environment }}"
      - name: Develop
        if: ${{ inputs.environment == 'Develop' }}
        run: echo "Develop step"
      - name: Production
        if: ${{ inputs.environment == 'Production' }}
        run: echo "Production step"
      - name: Command
        run: ./gradlew assemble'${{ inputs.environment }}'Release
